# Generated by Django 6.1.1 on 2026-10-03 08:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('format_type', models.CharField(default='Digital Guide & Curriculum', max_length=100)),
                ('estimated_duration', models.CharField(default='Self-paced (approx. 3-4 hours)', max_length=50)),
                ('level', models.CharField(default='All Levels / Practical Foundation', max_length=50)),
                ('what_is_included', models.TextField(default='8 comprehensive educational modules\n45-page digital companion guide\nActionable daily implementation checklists\nLifetime access & future module updates', help_text='One item per line (e.g. 8 structured video modules, 45-page downloadable PDF guide, Practical habit checklist)')),
                ('who_it_is_for', models.TextField(default='Individuals seeking clear, evidence-informed health principles\nBusy professionals wanting practical habits without extreme diets\nAnyone overwhelmed by conflicting online health advice', help_text='One item per line')),
                ('target_outcomes', models.TextField(default='Understand the core physiological basics of everyday wellbeing\nDevelop a sustainable, non-restrictive daily routine\nConfidently evaluate health claims and media headlines', help_text='One item per line')),
                ('cover_image_url', models.CharField(blank=True, help_text='URL for product cover visual', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, default='25 mins', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Module',
                'verbose_name_plural': 'Product Modules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Guide & Workbook'), ('checklist', 'Action Checklist'), ('template', 'Planning Template'), ('audio', 'Audio Walkthrough')], default='pdf', max_length=20)),
                ('file_size', models.CharField(blank=True, default='2.4 MB PDF', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Resource',
                'verbose_name_plural': 'Product Resources',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'featured'], name='products_pr_status_4ba6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
    ]
