# Generated by Django 6.1.1 on 2026-10-03 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField()),
                ('resource_type', models.CharField(choices=[('guide', 'Illustrated Guide'), ('checklist', 'Action Checklist'), ('reference', 'Reference Chart'), ('worksheet', 'Self-Assessment Worksheet')], default='guide', max_length=30)),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('format_label', models.CharField(default='PDF + Interactive', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Educational Resource',
                'verbose_name_plural': 'Educational Resources',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('video_id', models.CharField(help_text='YouTube Video ID (e.g. dQw4w9WgXcQ) or embed URL', max_length=100)),
                ('thumbnail_url', models.CharField(blank=True, help_text='Custom thumbnail image URL or auto-generated from YouTube', max_length=500)),
                ('duration', models.CharField(default='12:45', help_text='Duration string e.g. 14:30', max_length=30)),
                ('category', models.CharField(default='Health Principles', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['order', '-published_at'],
            },
        ),
    ]
