# Generated by Django 6.1.1 on 2026-10-03 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('interest_area', models.CharField(choices=[('all', 'All Upcoming Programs & Community'), ('telegram', 'Telegram Broadcasts & Live Q&A'), ('membership', 'Private Membership & Masterclasses'), ('nutrition', 'Everyday Nutrition Guides'), ('habits', 'Health Habit Systems')], default='all', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Waitlist Lead',
                'verbose_name_plural': 'Waitlist Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
